name: Deploy Website
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Deploy to surge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetch Dependencies
        run: yarn
      - name: Build Site
        run: yarn react-build
      - name: Deploy Site
        run: yarn surge ./dist ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
